// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5xUglndm2Y35YT3SIKMMBxShD7ViE2uE',
    appId: '1:11106684968:web:6c3141b0fb049f9652a51d',
    messagingSenderId: '11106684968',
    projectId: 'mi-store-app',
    authDomain: 'mi-store-app.firebaseapp.com',
    storageBucket: 'mi-store-app.appspot.com',
    measurementId: 'G-6VGWQ91RSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYegTFzmkLBK9nlpospBhzOJ3rhMVVtI',
    appId: '1:11106684968:android:330b04bc4e9ecdde52a51d',
    messagingSenderId: '11106684968',
    projectId: 'mi-store-app',
    storageBucket: 'mi-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_vZiJK0V6l5UJKmghS6QwMpLhMKz-8A',
    appId: '1:11106684968:ios:ada259da7b53ca2d52a51d',
    messagingSenderId: '11106684968',
    projectId: 'mi-store-app',
    storageBucket: 'mi-store-app.appspot.com',
    iosBundleId: 'com.example.miStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_vZiJK0V6l5UJKmghS6QwMpLhMKz-8A',
    appId: '1:11106684968:ios:ada259da7b53ca2d52a51d',
    messagingSenderId: '11106684968',
    projectId: 'mi-store-app',
    storageBucket: 'mi-store-app.appspot.com',
    iosBundleId: 'com.example.miStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5xUglndm2Y35YT3SIKMMBxShD7ViE2uE',
    appId: '1:11106684968:web:d9b6737265a308c852a51d',
    messagingSenderId: '11106684968',
    projectId: 'mi-store-app',
    authDomain: 'mi-store-app.firebaseapp.com',
    storageBucket: 'mi-store-app.appspot.com',
    measurementId: 'G-LGCGJDLPW9',
  );

}